services:
    frontend:
        build:
            context: ./packages/frontend
            dockerfile: Dockerfile
        ports:
            - '4173:4173'
        depends_on:
            - backend
        env_file:
            - ./packages/frontend/.env
        restart: unless-stopped

    backend:
        build:
            context: ./packages/backend
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        env_file:
            - ./packages/backend/.env
        restart: unless-stopped
